"""Opt-in synthetic demonstration data.

Every demo document is generated here, is labelled SYNTHETIC in its content,
title, source and laboratory name, and is processed by the same ingestion
pipeline as a real upload. The two older reports are confirmed automatically
so the timeline has history; the newest one is left for the user to review.
"""
from datetime import date, timedelta

from fastapi import APIRouter, Depends, HTTPException
from sqlmodel import Session, select

from ..database import get_session
from ..dependencies.auth import get_current_user
from ..models import ExtractedMeasurement, Patient, Report, User
from ..routers.medical_data import log_action
from ..services import report_pipeline as pipeline
from ..services.storage import delete_file, store_file
from ..services.synthetic_pdf import text_pdf

router = APIRouter(prefix="/api/v1/demo", tags=["Demo data"])

DEMO_SOURCE = "HoloMed demo (synthetic)"
DEMO_LAB = "Demo Laboratory (synthetic)"

# (days before today, auto-confirm, results). Values and flags are invented for demonstration.
_DEMO_REPORTS = [
    (690, True, [("HbA1c", "6.1", "%", "4.0 - 5.6", "H"), ("LDL Cholesterol", "138", "mg/dL", "<100", "H"),
                 ("HDL Cholesterol", "44", "mg/dL", ">40", ""), ("Hemoglobin", "14.1", "g/dL", "13.0 - 17.0", ""),
                 ("WBC Count", "6.9", "x10^3/uL", "4.0 - 11.0", ""),
                 ("Fasting Blood Glucose", "108", "mg/dL", "70 - 99", "H"),
                 ("Serum Creatinine", "0.92", "mg/dL", "0.70 - 1.30", "")], "128/84"),
    (360, True, [("HbA1c", "5.8", "%", "4.0 - 5.6", "H"), ("LDL Cholesterol", "121", "mg/dL", "<100", "H"),
                 ("HDL Cholesterol", "47", "mg/dL", ">40", ""), ("Hemoglobin", "13.8", "g/dL", "13.0 - 17.0", ""),
                 ("WBC Count", "7.4", "x10^3/uL", "4.0 - 11.0", ""),
                 ("Fasting Blood Glucose", "101", "mg/dL", "70 - 99", "H"),
                 ("Serum Creatinine", "0.95", "mg/dL", "0.70 - 1.30", "")], "124/80"),
    (20, False, [("HbA1c", "5.6", "%", "4.0 - 5.6", ""), ("LDL Cholesterol", "104", "mg/dL", "<100", "H"),
                 ("HDL Cholesterol", "51", "mg/dL", ">40", ""), ("Hemoglobin", "14.3", "g/dL", "13.0 - 17.0", ""),
                 ("WBC Count", "6.5", "x10^3/uL", "4.0 - 11.0", ""),
                 ("Fasting Blood Glucose", "96", "mg/dL", "70 - 99", ""),
                 ("Serum Creatinine", "0.98", "mg/dL", "0.70 - 1.30", "")], "121/78"),
]
_DEMO_REPORTS = [(d, c, [dict(zip(("name", "value", "unit", "range", "flag"), r)) for r in rows], bp)
                 for d, c, rows, bp in _DEMO_REPORTS]


def demo_document(day: date, rows, bp: str) -> bytes:
    lines = [
        "SYNTHETIC DEMONSTRATION REPORT - NOT REAL PATIENT DATA",
        DEMO_LAB,
        "Patient: Demo Patient (synthetic)",
        f"Collected: {day.isoformat()}",
        f"Report Date: {day.isoformat()}",
        "",
        "Test  Result  Unit  Reference Range  Flag",
    ]
    lines += [f"{r['name']} {r['value']} {r['unit']} {r['range']} {r['flag']}".rstrip() for r in rows]
    lines += [f"Blood Pressure: {bp} mmHg", "", "Generated by HoloMed for demonstration only."]
    return text_pdf(lines)


def _demo_reports(session: Session, user: User):
    return session.exec(select(Report).where(Report.owner_id == user.id, Report.source == DEMO_SOURCE)).all()


@router.get("")
def demo_status(user: User = Depends(get_current_user), session: Session = Depends(get_session)):
    return {"loaded": bool(_demo_reports(session, user)), "report_count": len(_demo_reports(session, user)),
            "label": "Synthetic demonstration data"}


@router.post("/load")
def load_demo(user: User = Depends(get_current_user), session: Session = Depends(get_session)):
    if _demo_reports(session, user):
        raise HTTPException(status_code=409, detail="Demo data is already loaded.")
    patient = session.exec(select(Patient).where(Patient.owner_id == user.id)).first()
    if not patient:
        patient = Patient(owner_id=user.id, display_name="Demo Patient")
        session.add(patient)
        session.commit()
        session.refresh(patient)

    engine = session.get_bind()
    created = []
    for days_ago, auto_confirm, rows, bp in _DEMO_REPORTS:
        day = date.today() - timedelta(days=days_ago)
        content = demo_document(day, rows, bp)
        filename = f"synthetic-blood-test-{day.isoformat()}.pdf"
        report = Report(owner_id=user.id, patient_id=patient.id,
                        title=f"Blood Test (synthetic demo) {day.isoformat()}", type="Blood Test",
                        source=DEMO_SOURCE, laboratory=DEMO_LAB, report_date=day.isoformat(),
                        status=pipeline.UPLOADED, original_filename=filename, mime_type="application/pdf",
                        file_size=len(content), storage_key=store_file(content, filename))
        session.add(report)
        session.commit()
        session.refresh(report)
        pipeline.add_source_reference(session, report)
        pipeline.start(session, report)
        pipeline.process(engine, report.id)
        session.expire_all()
        if auto_confirm:
            for cand in session.exec(select(ExtractedMeasurement).where(
                    ExtractedMeasurement.report_id == report.id)).all():
                cand.review_status = "accepted"
                session.add(cand)
            pipeline.confirm(session, session.get(Report, report.id), day)
            session.commit()
        created.append(report.id)
    log_action(session, user.id, "demo_data_loaded", {"reports": len(created)})
    session.commit()
    return {"loaded": True, "report_ids": created}


@router.delete("")
def clear_demo(user: User = Depends(get_current_user), session: Session = Depends(get_session)):
    reports = _demo_reports(session, user)
    for report in reports:
        pipeline.delete_derived(session, report.id)
        delete_file(report.storage_key, report.storage_provider)
        session.delete(report)
    log_action(session, user.id, "demo_data_removed", {"reports": len(reports)})
    session.commit()
    return {"loaded": False, "removed": len(reports)}
