"""Phase 8 features

Revision ID: 238f5e098b3e
Revises: fdde5eb0c094
Create Date: 2026-08-25 07:14:06.443117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '238f5e098b3e'
down_revision: Union[str, None] = 'fdde5eb0c094'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sourcereference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('report_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('storage_provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('storage_location', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sourcereference_owner_id'), 'sourcereference', ['owner_id'], unique=False)
    op.create_index(op.f('ix_sourcereference_report_id'), 'sourcereference', ['report_id'], unique=False)
    pass
    op.add_column('user', sa.Column('google_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_user_google_id'), 'user', ['google_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_google_id'), table_name='user')
    op.drop_column('user', 'google_id')
    pass
    op.drop_index(op.f('ix_sourcereference_report_id'), table_name='sourcereference')
    op.drop_index(op.f('ix_sourcereference_owner_id'), table_name='sourcereference')
    op.drop_table('sourcereference')
    # ### end Alembic commands ###
