"""Update Report model

Revision ID: ccb3f4cf726d
Revises: c3f9a1d2e4b6
Create Date: 2026-08-25 00:20:30.203049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ccb3f4cf726d'
down_revision: Union[str, None] = 'c3f9a1d2e4b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('patient_id', sa.Integer(), nullable=True))
    op.add_column('report', sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('report', sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('report', sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('report', sa.Column('report_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('report', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('report', sa.Column('hospital', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('report', sa.Column('laboratory', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('report', sa.Column('department', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('report', sa.Column('doctor', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_foreign_key(None, 'report', 'patient', ['patient_id'], ['id'])
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'report', type_='foreignkey')
    op.drop_column('report', 'doctor')
    op.drop_column('report', 'department')
    op.drop_column('report', 'laboratory')
    op.drop_column('report', 'hospital')
    op.drop_column('report', 'status')
    op.drop_column('report', 'report_date')
    op.drop_column('report', 'source')
    op.drop_column('report', 'type')
    op.drop_column('report', 'title')
    op.drop_column('report', 'patient_id')
    # ### end Alembic commands ###
