"""Phase 7 baseline

Revision ID: fdde5eb0c094
Revises: ccb3f4cf726d
Create Date: 2026-08-25 07:02:46.591386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fdde5eb0c094'
down_revision: Union[str, None] = 'ccb3f4cf726d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('report', sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('report', sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('report', sa.Column('report_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('report', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('report', sa.Column('hospital', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('report', sa.Column('laboratory', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('report', sa.Column('department', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('report', sa.Column('doctor', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    pass
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    pass
    op.drop_column('report', 'doctor')
    op.drop_column('report', 'department')
    op.drop_column('report', 'laboratory')
    op.drop_column('report', 'hospital')
    op.drop_column('report', 'status')
    op.drop_column('report', 'report_date')
    op.drop_column('report', 'source')
    op.drop_column('report', 'type')
    op.drop_column('report', 'title')
    # ### end Alembic commands ###
